name: smena_demo
description: Demo project for SMENA
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: 8.0.1
  get_it: 7.2.0
  injectable: 2.1.2
  go_router: 3.0.4
  dio: 4.0.4
  intl: 0.17.0
  hive: 2.0.6
  hive_flutter: 1.1.0
  freezed_annotation: 2.2.0
  freezed: 2.3.5
  json_annotation: 4.8.1
  json_serializable: 6.6.2
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true